### ISSUE TITLE
Support for making a clone/duplicate/deep copy of rvest objects

### ISSUE THREAD

**Issue by geotheory** [tidyverse/rvest#335] opened 2021-09-09 22:49 UTC
I'm perhaps mistaken but {rvest} doesn't seem to offer any way to extract text from a parent object only (ignoring children)?  One workaround uses `xml2::xml_remove()`, which mutates the original object.

I've tried using `rlang::duplicate()` to generate a clone/duplicate (where _"modifying the copy leaves the original object intact"_), but the clone does not appear to be truly independent. For example:

```
require(rvest)

h = '<ul>
<li id="target">
text to extract
<ul><li>text to ignore</li><li>this too</li></ul>
</li>
</ul>'

doc = xml2::read_html(h)
x = html_node(doc, '#target')

html_text(x)
#> [1] "\ntext to extract\ntext to ignorethis too"
```

Now clone x, remove its children, and extract the text:

```
x2 = rlang::duplicate(x, shallow = FALSE)
children = html_children(x2)
xml2::xml_remove(children)
html_text(x2)
#> [1] "\ntext to extract\n"
```

That works as intended, however x has also been mutated:

```
html_text(x)
#> [1] "\ntext to extract\n"
```

Is there any way to clone `x` in such a way that the copy can be mutated to extract text (without that of its children), such that `x` is not mutated?

I already reported this to [{rlang}](https://github.com/r-lib/rlang/issues/1270) and they suggested to post here.

**Comment by hadley** [comment] 2021-12-08 14:51
I think this is a duplicate of https://github.com/r-lib/xml2/issues/341

**Closed by hadley** 2021-12-08 14:51 UTC

**Comment by geotheory** [comment] 2021-12-08 20:13
I suppose I could've just said `xml_clone() please :)`!
