### ISSUE TITLE
rvest set_values checkbox error

### ISSUE THREAD

**Issue by kurtis14** [tidyverse/rvest#221] opened 2018-07-10 23:38 UTC
See stackoverflow post: https://stackoverflow.com/questions/51216772/rvest-set-values-checkbox-error 
@hadley

**Comment by hadley** [comment] 2019-03-17 17:36
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by kurtis14** [comment] 2019-03-17 20:09
Hi @hadley thanks for looking at this issue. I am trying to submit a form using rvest and then scrape the results.

The form has several checkboxes (with different names), which are unchecked by default, but I cannot figure out how to submit the form with one or more of them checked.

In the example below, I want to use set_values to set 'fh_diab' to checked, then submit the form. I have tried setting 'fh_diab' to TRUE, 'true', 'checked', '1', using and not using quotes on the RHS, but nothing I have tried works.

When I scrape the data, the result returned is 12.2%, when it should be 19.2% with 'fh_diab' checked.

`library(rvest)`
`url <- "https://qdiabetes.org/index.php"`
`page <- html_session(url)`
`form <- html_form(page)`
`form`
`form[[2]] <- set_values(form[[2]],'ethnicity'='1','sex'='0',
                        'weight'='80','height'='160','smoke_cat'='4','fh_diab'=1)`
`session <- submit_form(page,form[[2]])`
`table <- session %>% html_nodes("table")`
`table[[20]] %>% html_table()`

PS: the reprex link is broken.

**Comment by hadley** [comment] 2019-03-17 20:39
Sounds like a duplicate of #127

**Closed by hadley** 2019-03-17 20:39 UTC
Labels: form 🧾, reprex
