### ISSUE TITLE
Allow set_value() to set values not present in form

### ISSUE THREAD

**Issue by ethanbsmith** [tidyverse/rvest#222] opened 2018-07-16 02:32 UTC
I'm trying to download [the full] dynamically expanded [holdings] table using `rvest`, but am getting an Unknown field names error.

```R
s <- html_session("http://innovatoretfs.com/etf/?ticker=ffty")
f <- html_form(s)[[1]]
#the following line fails:
f.new <- set_values(f, `__EVENTTARGET` = "ctl00$BodyPlaceHolder$ViewHoldingsLinkButton")

##subsequent lines are not tested##
doc <- submit_form(s, f.new)
tabs <- xml_find_all(doc, "//table")
holdings <- html_table(tabs, fill = T, trim = T)[[5]]

```

I'm not great with HTML/HTTP but from what i can chase through, it seems to me that to expand the table requires a postback of the form with this new field value set

after inspecting the `set_values` function, it seems that it only allows existing fields to be assigned values.

is there any way to add a new field and a submit button to a form with `rvest`?

**Comment by ethanbsmith** [comment] 2018-07-16 03:04
also related to https://stackoverflow.com/questions/33885629/submit-form-with-no-submit-button-in-rvest?rq=1

**Comment by hadley** [comment] 2019-03-04 19:56
Please ask your question here, rather than pointing me to a question asked elsewhere.

**Comment by ethanbsmith** [comment] 2019-03-04 23:02
I'm trying to download [the full] dynamically expanded [holdings] table using `rvest`, but am getting an Unknown field names error.

```
s <- html_session("http://innovatoretfs.com/etf/?ticker=ffty")
f <- html_form(s)[[1]]
#the following line fails:
f.new <- set_values(f, `__EVENTTARGET` = "ctl00$BodyPlaceHolder$ViewHoldingsLinkButton")

##subsequent lines are not tested##
doc <- submit_form(s, f.new)
tabs <- xml_find_all(doc, "//table")
holdings <- html_table(tabs, fill = T, trim = T)[[5]]

```

I'm not great with HTML/HTTP but from what i can chase through, it seems to me that to expand the table requires a postback of the form with this new field value set

after inspecting the `set_values` function, it seems that it only allows existing fields to be assigned values.

is there any way to add a new field to a form under `rvest`?

**Comment by hadley** [comment] 2020-12-15 14:48
Hmmm, the problem is that this is currently an error, presumably because I want to help avoid accidentally setting the wrong values. That seems reasonable to me, so I think this request is out of scope for rvest. (But I am currently reconsidering the whole flow of the form submission process so it's possible I might change my mind)

**Closed by hadley** 2020-12-15 14:48 UTC
Labels: feature, form 🧾

**Comment by staropram** [comment] 2022-03-09 10:22
It would be great if one could add new fields to a form. I have a situation where the website I'm scraping from uses a progressive sequence of submits and the javascript adds the new field before submitting at each step so it isn't in the original form. If I could add to the form, it would work.

Perhaps something like html_form_add_field("blah"=3)
