### ISSUE TITLE
Promote website browsing capabilities in separate vignette

### ISSUE THREAD

**Issue by alex23lemm** [tidyverse/rvest#153] opened 2016-06-12 18:27 UTC
In the README you ask for feedback in regards to the package's website navigation options (`html_session`, `submit_form`, etc.)

I really like those features and use them since their first release. IMHO they are the most straight-forward and most reliable option in the R domain to fully automate data retrieval from web-based systems which do not provide an API.

Alternatives like RSelenium are less robust and not reliable (See discussion [here](https://github.com/ropensci/RSelenium/issues/32)) which is not the fault of RSelenium but of the underlying dependencies (e.g. phantomjs driver)

Therefore, I would vote for promoting those rvest features in a separate vignette.

**Comment by hadley** [comment] 2019-03-17 18:13
Thanks for the feedback!

Duplicate of #182

**Closed by hadley** 2019-03-17 18:13 UTC
