### ISSUE TITLE
If image URL is not in html_attr("src"), how to scrape the image url?

### ISSUE THREAD

**Issue by himanshudhingra** [tidyverse/rvest#177] opened 2016-11-01 09:43 UTC
source code is: 
`<img alt="product name " class="cz-img large_img image_size img_slider_1060571227 img_2" id="d3-view_2" itemprop="image" style="height: auto;" src="">
          <script>
            var image_url = "https://images.xyz.com/i/314183/large/swatch-image20160708-13472-dh956c.jpg?1467959305";
            $('.img_2').attr('src',image_url);
            $('.img_2').on('load', function(){
              $('.image_message_color').show();
            });
          </script>`

I usually use:

`#Get image_url
image_url<-link %>% 
  html_nodes("#d3-view_1") %>% 
  html_attr("src")
image_url`

But here, the src is empty. and what I want to extract images.xyz.com/i/314183/large/swatch-image20160708-13472-dh956c.jpg?1467959305

Please help.

**Comment by sjp** [comment] 2016-11-15 00:42
This isn't a bug with `rvest` as such but caused by this web page's dependency on JS to render images correctly.

A solution for you would be to search for all script tags (i.e. `html_nodes("script")` and then search the contents of the script tags for `image_url` and use some regex to get the value of the URL.

It's hacky, and site-dependent but if they're depending on inline JS to display images then it's a necessary evil.

**Comment by cruzmiler** [comment] 2017-01-16 06:24
Hi Himanshu,

This is not an ideal way but in such a situation when the standard functions won't extract, you could go the regex way as sjp also suggests. 

You can coerce the the source code to a character and assign to a variable _rawcode_. Then you may use the code as follows to extract what's required:
```
img_link = unlist(regmatches(rawcode,gregexpr("(?<=var image_url = \").+\.jpg",rawcode, perl = TRUE)))
```

**Closed** 2019-03-04 19:57 UTC
