### ISSUE TITLE
html_table converts hex values to doubles

### ISSUE THREAD

**Issue by JackWilb** [tidyverse/rvest#233] opened 2019-02-18 20:32 UTC
I'm trying to scrape some ethereum addresses from etherscan.io and I'm having an issue where html_table is converting the addresses from hex to double. Here's my code:

`page_data = read_html("https://etherscan.io/accounts/1?&l=Exchange")`
 `table = page_data %>% html_node("table") %>% html_table()`

Actual First Row:
0xff6b1cdfd2d3e37977d7938aa06b6d89d6675e27	AllBit	834.3993817 Ether	41,893

Scraped First Row:
1458181341603533765023513868408976323559018201088  AllBit    834.3993817 Ether   41,893

Is there an easy way to fix this behavior or am I going to have to work around this in another way?

Thanks!

**Comment by hadley** [comment] 2019-03-04 19:56
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2019-03-29 14:52
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2019-03-29 14:52 UTC
Labels: reprex, table 🏓
